site_name: Islandora 8
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora 8

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora/documentation
edit_uri: 'edit/main/docs/'

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/claw.png'
  language: 'en'
markdown_extensions:
  - admonition
  - toc:
        permalink: True
extra_css:
  - css/custom.css
plugins:
  - search
  - git-revision-date-localized

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/islandora'

copyright: <b>This documentation is user-sourced!</b> Suggestions and comments are welcome in our <u><a href="https://github.com/Islandora/documentation/issues" target="_blank">issue queue</a></u>.

nav:
  - 'About': 'index.md'
  # Conceptual, all user roles: should contain high-level information about
  # what everybody needs to know to understand Islandora and interact with it
  # Possibly add page/section: How to use this documentation (containing user role definitions)
  - Concepts:
      - 'Software Stack': 'concepts/stack.md'
          # Includes bento box and architecture diagram,
          # Includes short summaries of each part. 
          # 
          # Replaces user-intro.md#architecture.
          # Conceptual/ reference, all user roles/ sys admins/ developers: 
      - 'Modelling content in Islandora 8 vs. 7': 'user-documentation/objects_to_resource_nodes.md'
              # conceptual, all user roles
              # moved from User documentation > Content in Islandora 8
      - Islandora Defaults: 'reference/islandora_defaults_reference.md'
  - Installation:
      # Procedural, different user roles: clarify who the audience is for a 
      # particular recipe. The ISLE documentation page was written with a 
      # 'non-technical' user in mind who wants to test. The Manual installation 
      # guides mention that users will need additional knowledge about server administration.
      - 'Docker Compose (ISLE-DC)': 'installation/docker-compose.md'
      - 'Ansible Playbook': 'installation/playbook.md'
      - Manual Installation: 
        - 'Introduction': 'installation/manual/introduction.md'
        - 'Component overview': 'installation/component_overview.md'
        - 'Preparing a LAPP Webserver': 'installation/manual/preparing_a_webserver.md'
        - 'Installing Composer, Drush, and Drupal': 'installation/manual/installing_composer_drush_and_drupal.md'
        - 'Installing Tomcat and Cantaloupe': 'installation/manual/installing_tomcat_and_cantaloupe.md'
        - 'Installing Fedora, Syn, and Blazegraph': 'installation/manual/installing_fedora_syn_and_blazegraph.md'
        - 'Installing Solr': 'installation/manual/installing_solr.md'
        - 'Installing Crayfish': 'installation/manual/installing_crayfish.md'
        - 'Installing Karaf and Alpaca': 'installation/manual/installing_karaf_and_alpaca.md'
        - 'Configuring Drupal': 'installation/manual/configuring_drupal.md'
      - 'Installing Modules': 'technical-documentation/install-enable-drupal-modules.md'
          # procedural, sysadmin
          # moved from System Administrator Documentation
  - Tutorials:
      # Audience for this section is someone who is extremely new to doing 
      # the kinds of things that we are introducing. This is someone's first
      # foray into this domain so each tutorial should accomplish something 
      # satisfying, and work 100% of the time.

      # Tutorials are not conceptual. They tell you exactly what to do without 
      # explaining why, and let the user decide if they want to look deeper at 
      # what these concepts are. 
      - 'Create a Resource Node': 'tutorials/create-a-resource-node.md'
            # procedural, for people learning what islandora is. 
      - 'Video Documentation': 'user-documentation/video-docs.md'
          # mostly procedural, repository managers
 
  - Documentation:
      - 'Introduction': 'user-documentation/user-intro.md'
          # Conceptual, 'site admins/repository managers'
          # move out high-level conceptual information (#architecture section)
      - 'Intro to Linked Data': 'user-documentation/intro-to-ld-for-islandora-8.md'
          # conceptual, repository managers
      - 'Versioning': 'user-documentation/versioning.md'
          # conceptual/ reference, repository managers/ developers
      - Content in Islandora 8:
          # largely conceptual, repository managers and to some extent curators
          # currently duplicates a section also present under "User documentation", 
          # develop into procedural documentation for repository 
          # admins about how to manage content in I8
        - 'Resource Nodes': 'user-documentation/resource-nodes.md'
              # largely conceptual, repository managers; move out procedural 
              # information (e.g. move procedure for setting display hints to 
              # documentation about contexts)
        - 'Media': 'user-documentation/media.md'
              # conceptual and procedural, repository managers
              # move out procedural description for deleting Media
        - 'Collections': 'user-documentation/collections.md'
              # conceptual and procedural, repository managers/ curators
              # move out procedural description for creating and populating collections
        - 'Paged Content': 'user-documentation/paged-content.md'
              # conceptual and procedural, repository managers/ curators
              # move out procedural description for ordering pages
        - 'Metadata': 'user-documentation/metadata.md'
              # largely conceptual, repository managers/ curators
      - Configuring Islandora:
          - 'Modify or Create a Content Type': 'user-documentation/content_types.md'
                  # procedural, repository managers
                  # add resource page on learning YAML
          - 'Create or Update a View': 'user-documentation/create_update_views.md'
                  # procedural, repository managers
          - 'Configure Search': 'user-documentation/searching.md'
              # procedural, repository manager
          - 'Configure Context': 'user-documentation/context.md'
              # conceptual and procedural, repository managers
          - 'Configure Blocks': 'user-documentation/blocks.md'
              # procedural, repository managers
              # add/link to conceptual documentation about block in Drupal
          - 'Access Control': 'user-documentation/access-control.md'
          - 'Multilingual': 'user-documentation/multilingual.md'
              # conceptual/ procedual/ reference, repository managers
          - 'Accessibility': 'user-documentation/accessibility.md'
              # conceptual
          - 'Extending Islandora': 'user-documentation/extending.md'
              # conceptual, repository managers/ developers
          - 'Viewers': 'user-documentation/file_viewers.md'
              # conceptual, understanding a very complex network of config. For repo managers/devs.
          - 'IIIF': 'user-documentation/iiif.md'
              # conceptual/ procedural, repository managers
              # add reference documentation about IIIF presentation API implementation
          - 'OAI-PMH': 'user-documentation/oai.md'
              # conceptual, repository managers
              # add reference documentation for developers?
          - 'RDF Generation': 'islandora/rdf-mapping.md'
              # conceptual/reference/procedure, repository managers/ developers
          - 'Drupal Bundle Configurations': 'islandora/drupal-bundle-configurations.md'
              # conceptual/procedure, repository managers
          - 'Flysystem': 'technical-documentation/flysystem.md'
              # moved from Developer documentation
      - Operating an Islandora Repository:
          - 'Create and Manage User Accounts': 'user-documentation/users.md'
              # procedural, repository managers
              # add reference information on user roles that come with Islandora/Islandora Defaults out of the box
          - 'Usage Stats': 'user-documentation/usage-stats.md'
              # largely conceptual, repository managers
  - System Administrator Documentation:
    - 'Updating Drupal': 'technical-documentation/updating_drupal.md'
    - 'Uploading large files': 'technical-documentation/uploading-large-files.md'
    - 'JWT Authentication': 'technical-documentation/jwt.md'
          # moved from Developer documentation
  - Documentation for Developers:
    - REST Documentation:
      - 'Introduction': 'technical-documentation/using-rest-endpoints.md'
      - 'GET': 'technical-documentation/rest-get.md'
      - 'POST/PUT': 'technical-documentation/rest-create.md'
      - 'PATCH': 'technical-documentation/rest-patch.md'
      - 'DELETE': 'technical-documentation/rest-delete.md'
      - 'Signposting': 'technical-documentation/rest-signposting.md'
    - Tests:
      - 'Running Tests': 'technical-documentation/running-automated-tests.md'
      - 'Testing Notes': 'technical-documentation/testing-notes.md'
    - 'Updating drupal-project': 'technical-documentation/drupal-project.md'
    - 'Versioning Policy': 'technical-documentation/versioning.md'
    - 'Adding back ?_format=jsonld': 'technical-documentation/adding_format_jsonld.md'
    - 'Updating a `deb` and adding it to Lyrasis PPA': 'technical-documentation/ppa-documentation.md'
    - Alpaca:
      - 'Alpaca Technical Stack': 'alpaca/alpaca-technical-stack.md'
      - 'Alpaca Tips': 'technical-documentation/alpaca_tips.md'
  - Migration:
      - 'Migration Overview': 'technical-documentation/migration-overview.md'
      - 'CSV': 'technical-documentation/migrate-csv.md'
      - 'Islandora 7': 'technical-documentation/migrate-7x.md'
  - Contributing:
      - 'How to contribute': 'contributing/CONTRIBUTING.md'
      - Virtual Machines:
        - 'Hacking on Islandora': 'contributing/hacking-on-islandora.md'
        - 'Resizing a VM': 'technical-documentation/resizing_vm.md'
      - 'Checking Coding Standards': 'technical-documentation/checking-coding-standards.md'
      - 'Contributing Workflow': 'contributing/contributing-workflow.md'
      - 'Creating GitHub Issues': 'contributing/create_issues.md'
      - 'Editing Documentation': 'contributing/editing-docs.md' 
      - 'How to Build Documentation': 'technical-documentation/docs-build.md'
          # moved from Developer documentation
      - 'Documentation Style Guide': 'contributing/docs_style_guide.md'
      - 'Committers': 'contributing/committers.md'
  - Glossary: 'user-documentation/glossary.md'
